export { default as Home } from './Home/home.page'
export { default as Shop } from './Shop/shop.page'
export { default as About } from './About/about.page'
export { default as Contact } from './Contact/contact.page'
export { default as Error } from './Error/error.page'